services:
    nginx:
        container_name: nginx
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        ports:
            - "443:443"
        networks:
            - inception_network
        volumes:
            - inception_wordpress:/var/www/wordpress

    wordpress:
        container_name: wordpress
        build: requirements/wordpress
        env_file: .env
        ports:
            - "9000:9000"
        networks:
            - inception_network
        volumes:
            - inception_wordpress:/var/www/wordpress

    mariadb:
        container_name: mariadb
        build: requirements/mariadb
        env_file: .env
        ports:
            - "3306:3306"
        networks:
            - inception_network
        volumes:
            - inception_mariadb:/var/lib/mysql

volumes:
    inception_wordpress:
        driver: local
        driver_opts:
            type: none
            device: /home/parallels/data/wordpress
            o: bind
    inception_mariadb:
        driver: local
        driver_opts:
            type: none
            device: /home/parallels/data/mysql
            o: bind
networks:
    inception_network:
      driver: bridge
      external: false
